### PR TITLE
Use new LeaseRecoverable interface added in HADOOP-18671

### LINKED ISSUE #3494: Implement HADOOP-18671 changes
HADOOP-18671 moves `recoverLease` and `setSafeMode` up to the interface level. We call these methods [here](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java#L58) and [here](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java#L453). This will require a Hadoop version bump to 3.3.6 when it's released.

### PR DESCRIPTION
**Pull request by dlmarion**
This change uses FileSystem.hasPathCapability to determine if the FileSystem implementation has the ability to recover leases.

Closes #3494

### CODE REVIEW

**Comment by dlmarion** [comment]
https://issues.apache.org/jira/browse/HADOOP-18671 was backported to Hadoop version 3.2.5. If we want to include this change, then we will need to bump the minimum supported version.

File: server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java [hunk 1]
```diff
@@ -67,8 +67,6 @@ public long close(AccumuloConfiguration conf, Configuration hadoopConf, VolumeMa
         ns.append(source).close();
         log.info("Recovered lease on {} using append", source);
       }
-    } else if (ns instanceof LocalFileSystem || ns instanceof RawLocalFileSystem) {
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java:70]: Do you happen to know if the local filessystem impls will have the `CommonPathCapabilities.LEASE_RECOVERABLE` capability?

**Review by keith-turner — APPROVED** [review]
> https://issues.apache.org/jira/browse/HADOOP-18671 was backported to Hadoop version 3.2.5. If we want to include this change, then we will need to bump the minimum supported version.

One of the github action builds failed with the following,  assuming is this failure related to this comment?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project accumulo-server-base: Compilation failure: Compilation failure: 
[ERROR] /home/runner/work/accumulo/accumulo/server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java:[28,28] cannot find symbol
[ERROR]   symbol:   class CommonPathCapabilities
[ERROR]   location: package org.apache.hadoop.fs
[ERROR] /home/runner/work/accumulo/accumulo/server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java:[30,28] cannot find symbol
[ERROR]   symbol:   class LeaseRecoverable
[ERROR]   location: package org.apache.hadoop.fs
[ERROR] -> [Help 1]
```

File: server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java (hunk 1 above)
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java:70]: It looks like only DistributedFileSystem and ViewDistributedFileSystem implement the LeaseRecoverable interface.

**Comment by dlmarion** [comment]
> > https://issues.apache.org/jira/browse/HADOOP-18671 was backported to Hadoop version 3.2.5. If we want to include this change, then we will need to bump the minimum supported version.
> 
> One of the github action builds failed with the following, assuming is this failure related to this comment?
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project accumulo-server-base: Compilation failure: Compilation failure: 
> [ERROR] /home/runner/work/accumulo/accumulo/server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java:[28,28] cannot find symbol
> [ERROR]   symbol:   class CommonPathCapabilities
> [ERROR]   location: package org.apache.hadoop.fs
> [ERROR] /home/runner/work/accumulo/accumulo/server/base/src/main/java/org/apache/accumulo/server/manager/recovery/HadoopLogCloser.java:[30,28] cannot find symbol
> [ERROR]   symbol:   class LeaseRecoverable
> [ERROR]   location: package org.apache.hadoop.fs
> [ERROR] -> [Help 1]
> ```

Yes, exactly. The GH action builds with Hadoop 3.0.3, so if we want to merge this, then we need to bump the minimum supported version.

**Comment by dlmarion** [comment]
It looks like HADOOP-18671 was backported to the Hadoop 3.2.5 branch, but version 3.2.5 has not been released yet. That means that only Hadoop version 3.3.6 and 3.4.0+ have this new interface.

**Comment by steveloughran** [comment]
we're not doing any maintenance or releass on 3.2.x I'm afraid: if you need it, you'll have to build it yourself.

Sorry.

FWIW, key reason it is the continuous struggle to upgrade dependencies, even getting 3.4.x current is a losing battle as some of the updates are not backwards compatible.
